version: '3.4'

networks:
  pokemon-network:

services:
  demopokemonreviewdb:
    container_name: pokemon-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 8002:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P@sssw0rd
    networks:
      - pokemon-network


  pokemonreviewapp:
    container_name: demo-pokemon-api
    image: ${DOCKER_REGISTRY-}pokemonreviewapp
    build:
      context: .
      dockerfile: PokemonReviewApp/Dockerfile
    ports:
    - 8001:80
    depends_on:
      - demopokemonreviewdb
    environment:
      - DB_HOST=demopokemonreviewdb
      - DB_NAME=PokemonDB
      - DB_SA_PASSWORD=P@sssw0rd
    networks:
      - pokemon-network